version: "3.5"

networks:
        localhost:
                name: inet

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/buthor/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/buthor/data/mariadb
                        o: bind
                        type: none


services:
        nginx:
                depends_on:
                        - wordpress
                container_name: nginx_debian
                build: ./nginx
                image: nginx
                ports:
                        - "443:443"
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always
        mariadb:  
                container_name: mariadb_debian
                build: ./mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - localhost
                image: mariadb
                restart: always
        wordpress:
                depends_on:
                        - mariadb
                container_name: wordpress_debian
                build: ./wordpress
                image: wordpress
                volumes:
                        - wordpress:/var/www/wordpress
                networks:
                        - localhost
                restart: always
